import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
export const dynamic = 'force-dynamic'
export const revalidate = 500


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className} suppressHydrationWarning={true}>
      <Navbar/>
      {children}

      </body>
    </html>
  );
}
